substitutions:
  #Name your Gateway
  device_name: a4-button
  #Home Assistant Name
  friendly_name: a4 button
  #Secret YAML is used for next data:
  api_pw: !secret api_password
  ota_pw: !secret ota_password

esphome:
  name: ${device_name}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  # Set up a wifi access point
  ap:
    ssid: '${friendly_name}'

captive_portal:

improv_serial:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
    name: "Button"
    device_class: window

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ${api_pw}
  reboot_timeout: 0s

# Enable OTA
ota:
  password: ${ota_pw}

#Enable WEB
web_server:
  port: 80

# Enable HA Time
time:
  - platform: homeassistant
    id: homeassistant_time
