substitutions:
  #Name your Gateway
  device_name: a4-button
  #Home Assistant Name
  friendly_name: a4 button
  #Secret YAML is used for next data:
  api_pw: !secret api_password
  ota_pw: !secret ota_password

esphome:
  name: ${device_name}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  # Set up a wifi access point
  ap:
    ssid: '${friendly_name}'

captive_portal:

improv_serial:

output:
  - platform: ledc
    pin: GPIO1
    id: buzzer

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
    name: "Button"
    device_class: window
    on_press:
      then:
        - switch.turn_on: led_sw
        - output.turn_on: buzzer
        - output.ledc.set_frequency:
            id: buzzer
            frequency: "4000Hz"
        - output.set_level:
            id: buzzer
            level: "50%"
        - light.turn_on:
            id: led_1
            brightness: 30%
            red: 40%
            green: 40%
            blue: 1.0

switch:
  - platform: gpio
    id: led_sw
    pin: 
      number: 5
      inverted: true

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO4
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "My Light"
    id: led_1

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ${api_pw}
  reboot_timeout: 0s

# Enable OTA
ota:
  password: ${ota_pw}

#Enable WEB
web_server:
  port: 80

# Enable HA Time
time:
  - platform: homeassistant
    id: homeassistant_time
