substitutions:
  device_name: a4-button
  friendly_name: a4 button
  #Secret YAML is used for next data:
  api_pw: !secret api_password
  ota_pw: !secret ota_password

debug:

esphome:
  name: ${device_name}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true

  # Set up a wifi access point
  ap:
    ssid: '${friendly_name}'

mqtt:
  broker: YOUR_BROKER_ADDRESS
  port: 1883

# text component for MQTT params
text:
  - platform: template
    name: "1. MQTT broker"
    id: text_mqtt_broker
    mode: text
    optimistic: true
    restore_value: true
  - platform: template
    name: "2. MQTT port"
    id: text_mqtt_port
    mode: text
    optimistic: true
    restore_value: true
  - platform: template
    name: "3. MQTT username" 
    id: text_mqtt_username
    mode: text
    optimistic: true
    restore_value: true
  - platform: template
    name: "4. MQTT password" 
    id: text_mqtt_password
    mode: password
    optimistic: true
    restore_value: true

button:
  - platform: template
    name: 5. Update MQTT config
    id: my_button
    icon: "mdi:emoticon-outline"
    on_press:
      then:
        - lambda: |-
            static MQTTClientComponent *mq = esphome::mqtt::global_mqtt_client;
            mq->set_broker_port((uint16_t)stoi(id(text_mqtt_port).state));
            mq->set_broker_address(id(text_mqtt_broker).state);
            mq->set_username(id(text_mqtt_username).state);
            mq->set_password(id(text_mqtt_password).state);

captive_portal:

improv_serial:

output:
  - platform: ledc
    pin: GPIO1
    id: buzzer

deep_sleep:
  id: gosleep
  wakeup_pin:
    number: GPIO3
    inverted: true
    mode: INPUT_PULLUP
    allow_other_uses: true

binary_sensor:
  - platform: gpio
    id: btn1
    pin:
      number: GPIO3
      allow_other_uses: true
      mode: INPUT_PULLUP
    name: "Button"
    device_class: window
    on_press:
      then:
        - switch.turn_on: led_sw
        - light.turn_on:
            id: led_1
            brightness: 30%
            red: 40%
            green: 40%
            blue: 1.0
        - delay: 2s
        - switch.turn_off: led_sw
        #- deep_sleep.enter:
        #  id: gosleep

switch:
  - platform: gpio
    id: led_sw
    pin: 
      number: GPIO5
      inverted: true

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO4
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "My Light"
    id: led_1

# Enable logging
logger:
  level: DEBUG

api:
  password: ${api_pw}
  reboot_timeout: 0s

# Enable OTA
ota:
  password: ${ota_pw}

#Enable WEB
web_server:
  port: 80

# Enable HA Time
time:
  - platform: homeassistant
    id: homeassistant_time
